### ISSUE TITLE
Feature | Run config file on a buffer

### ISSUE THREAD

**Issue by eugercek** [kmonad/kbd-mode#6]
I've written some functions to improve my kmonad config editing experience. Although README says `An Emacs mode for syntax highlighting kmonad's .kbd files.`, I thought it could be a nice fit on the package.
If it's a good fit, I'll create a PR.

### Features:
- Show errors of config file
- Run current config in a buffer, when the buffer is killed kill the kmonad process

#### Planned Features (Bloats 😃 )
- Always run the `kmonad-file` **only** in  a buffer
  - When user changes the config file kmonad will be called with the new config file
  - When buffer's focus has lost kmonad will stop, when buffer gains focus again kmonad will continue
- Show current kmonad config on modeline

My elisp-fu is not perfect, I may need some advice on the first planned feature.

### Demo
https://user-images.githubusercontent.com/58051033/152391120-49ae8f5e-27ab-4244-9cdb-af97c929c32e.mp4

**Comment by slotThe** [comment]
This looks great!

> Although README says `An Emacs mode for syntax highlighting kmonad's .kbd files.`, I thought it could be a nice fit on the package.

It's definitely a fit; the README more describes the current state of the project than what it could be some day.

> * Always run the `kmonad-file` **only** in  a buffer
>
>   * When user changes the config file kmonad will be called with the new config file
>   * When buffer's focus has lost kmonad will stop, when buffer gains focus again kmonad will continue

This sounds pretty neat.  I suppose we could create a new minor mode (`kbd-mode-test-mode` or something) and then add a hook to `window-configuration-change-hook` (though I'm not sure whether this is best practice but I can see some packages I'm using, like `notmuch`, are doing it).

If you want, you can just open a PR and we can take it from there

**Comment by eugercek** [comment]
I'm creating the PR.
